// Single source of truth: VERSION.txt.
// Syncs VERSION.txt → package.json "version".
// Run this before build/publish. (src/_version.ts is regenerated by the
// "version" npm script / build.tui.mjs, which read package.json.)
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const versionPath = resolve(root, "VERSION.txt");
const pkgPath = resolve(root, "package.json");

const version = readFileSync(versionPath, "utf-8").trim();
const m = version.match(/^(\d+)\.(\d+)\.(\d+)$/);
if (!m) {
  console.error(`[sync-version] VERSION.txt must be X.Y.Z, got: "${version}"`);
  process.exit(1);
}

const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
if (pkg.version !== version) {
  pkg.version = version;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
  console.log(`[sync-version] package.json version → ${version}`);
} else {
  console.log(`[sync-version] package.json already at ${version}`);
}
